spring.application.name=OrdemServico
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/bado_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=bado
spring.datasource.password=gmSenai

spring.jpa.show-sql=True